# This rule is not used by the project azdo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over opentools.mf.opentools.mf.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: azdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnerpool-admin-role
rules:
- apiGroups:
  - opentools.mf.opentools.mf
  resources:
  - runnerpools
  verbs:
  - '*'
- apiGroups:
  - opentools.mf.opentools.mf
  resources:
  - runnerpools/status
  verbs:
  - get
