# This rule is not used by the project azdo-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the opentools.mf.opentools.mf.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: azdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnerpool-editor-role
rules:
- apiGroups:
  - opentools.mf.opentools.mf
  resources:
  - runnerpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opentools.mf.opentools.mf
  resources:
  - runnerpools/status
  verbs:
  - get
