apiVersion: opentools.mf.opentools.mf/v1
kind: RunnerPool
metadata:
  labels:
    app.kubernetes.io/name: azdo-operator
    app.kubernetes.io/managed-by: kustomize
  name: runnerpool-sample
spec:
  # TODO(user): Add fields here
